services:
    backend:
        image: cineworld-backend:prod
        container_name: cine_world_backend
        ports:
            - "8000:8000"
        env_file:
            - .env
            
    frontend:
        image: cineworld-frontend:prod
        container_name: cine_world_frontend
        depends_on:
            - backend
            
    nginx:
        build: ./nginx
        container_name: cineworld-nginx
        ports:
            - "80:80"
        depends_on:
            - frontend
            - backend
